odom_frame: "odom"
map_frame: "map"
base_frame: "base_link"
throttle_scans: 1
map_update_interval: 5.0
resolution: 0.35
delta: 0.01
transform_publish_period: 0.05
use_scan_matching: true
use_scan_barycenter: true
minimum_travel_distance: 0.2
minimum_travel_heading: deg2rad(10)
scan_buffer_size: 70
scan_buffer_maximum_scan_distance: 20.0
link_match_minimum_response_fine: 0.8
link_scan_maximum_distance: 10.0
loop_search_maximum_distance: 4
do_loop_closing: true
loop_match_minimum_chain_size: 10
loop_match_maximum_variance_coarse: sqrt(0.4)
loop_match_minimum_response_coarse: 0.8
loop_match_minimum_response_fine: 0.8 
correlation_search_space_dimension: 0.3
correlation_search_space_resolution: 0.01
correlation_search_space_smear_deviation: 0.03
loop_search_space_dimension: 8.0
loop_search_space_resolution: 0.05
loop_search_space_smear_deviation: 0.03
distance_variance_penalty: sqrt(0.3)
angle_variance_penalty: sqrt(deg2rad(20))
fine_search_angle_offset: deg2rad(0.2)
coarse_search_angle_offset: deg2rad(20.0)
coarse_angle_resolution: deg2rad(2.0)
minimum_angle_penalty: 0.9
minimum_distance_penalty: 0.5
use_response_expansion: false